services:
  android-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - gradle-cache:/root/.gradle:cached
      - android-cache:/root/.android:cached
    environment:
      - GRADLE_USER_HOME=/root/.gradle
      - ANDROID_SDK_ROOT=/usr/local/android-sdk
      - KEY_ALIAS
      - KEY_PASSWORD
      - STORE_PASSWORD
    tty: true
    stdin_open: true

volumes:
  gradle-cache:
  android-cache: 