name: CI/CD Pipeline for Android App

on:
  push:
    branches:
      - master  # Trigger the pipeline on pushes to the master branch
  pull_request:
    branches:
      - master  # Trigger for pull requests targeting the master branch

permissions:
  contents: write  # Grant write access to the repository contents

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java 21 as you use it)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          components: |
            cmdline-tools;latest
            platform-tools
            platforms;android-35  # Specify the Android API level you need
            build-tools;33.0.0  # Specify the build tools version you need

      # Step 4: Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Step 5: Decode keystore and place it in the correct directory
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ./KEY_STORE/schmng.jks

      # Step 6: Verify the keystore file is present
      - name: List files in KEY_STORE
        run: |
          echo "Listing contents of ./KEY_STORE"
          ls -la ./KEY_STORE

      # Step 7: Run tests (optional)
      - name: Run unit tests
        run: ./gradlew test

      # Step 8: Build the Release APK
      - name: Build the project
        env:
          KEY_ALIAS: "key0"  # Directly set the key alias
          KEY_PASSWORD: "955326"  # Directly set the key password
          STORE_PASSWORD: "955326"  # Replace with your actual store password
          KEYSTORE_FILE: "./KEY_STORE/schmng.jks"  # Reference the keystore file in the project directory
        run: ./gradlew assembleRelease

      # Step 9: Create a Git tag
      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="v${{ github.run_number }}"  # Set the tag name to the run number
          echo "Creating tag: $TAG_NAME"
          git tag -d $TAG_NAME || true  # Delete the local tag if it exists
          git push origin :refs/tags/$TAG_NAME || true  # Delete the remote tag if it exists
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is set

      # Step 10: Create GitHub Release and Upload APK
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}  # Use the created tag
          name: Release v${{ github.run_number }}  # Name of the release
          body: "Release of APK version v${{ github.run_number }}"  # Description of the release
          files: app/build/outputs/apk/release/app-release.apk  # Path to the APK file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is set
