name: CI/CD Pipeline for Android App

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build, Deploy & Rollback Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          components: |
            cmdline-tools;latest
            platform-tools
            platforms;android-35
            build-tools;33.0.0

      - name: Grant gradlew permissions
        run: chmod +x ./gradlew

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          mkdir -p ./app/KEY_STORE
          echo "${KEYSTORE_BASE64}" | base64 --decode > ./app/KEY_STORE/schmng.jks

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build AAB
        run: ./gradlew bundleRelease
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="v${{ github.run_number }}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag -d $TAG_NAME || true
          git push origin :refs/tags/$TAG_NAME || true
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: "Release of version ${{ env.TAG_NAME }}"
          files: app/build/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload New Version to Production
        uses: r0adkll/upload-google-play@v1
        with:
          # Service account credentials from GitHub Secrets
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_JSON }}
          # Package name of the app
          packageName: com.ecorvi.schmng
          # Path of the App Bundle file
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          # Production track of google play
          track: production
          # Release status set to completed to send for review
          status: completed
          # App update priority
          inAppUpdatePriority: 0
  
